### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by i-saint** [i-saint/USDForMetasequoia#1]
# release 1.0.0
- [x] insert (additive import) mode
- [x] track material rename
- [x] japanese node name support
- [x] handle visibility
- [x] care transform
- [x] error message
- [x] sample index based seek (instead of time based seek)
---
# possibly in later releases
- [ ] variant selector (USD)
- [ ] japanese UI
- [ ] handle japanese file path
- [ ] handle symlinks (USD)
